version: '3.8'

services:
  monero:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mainnet-monero
    ports:
      - "18080:18080"
      - "18081:18081"
      - "18083:18083"
      - "18084:18084"
      - "18085:18085"
      - "18086:18086"
      - "18087:18087"
    volumes:
      - /monero/chain:/root/.bitmonero
      - /monero/wallet:/wallet
    command: >
      /usr/bin/supervisord